In [5]:
# ============================================================================
# QUESTION 1(b): PIVOT COLUMNS, PARTICULAR SOLUTION, AND NULL SPACE
# ============================================================================

import numpy as np

# ============================================================================
# INPUT FROM Q1(a) RESULTS
# ============================================================================

# Matrix A from Q1(a)
A = np.array([
    [-1, 0, 3, 5, -3],
    [4, -3, 3, -4, -3],
    [-4, 1, -4, 5, 1],
    [-2, 4, 0, 0, -1]
])

# Vector b from Q1(a)
b = np.array([[19], [1], [1], [1]])

# RREF of Augmented Matrix [A|b] from Q1(a)
rref_augmented = np.array([
    [1.0, 0.0, 0.0, 0.0, 12.5625, -12.5625],
    [0.0, 1.0, 0.0, 0.0, 6.0312, -6.0312],
    [0.0, 0.0, 1.0, 0.0, -5.0937, 7.0937],
    [0.0, 0.0, 0.0, 1.0, 4.9687, -2.9687]
])

# Extract RREF of A and b
rref_A = rref_augmented[:, :5]
rref_b = rref_augmented[:, 5:6]

print("="*60)
print("RREF_A",rref_A)
print("RREF_b",rref_b)

print("="*60)
print("Q1(b): PIVOT COLUMNS, PARTICULAR SOLUTION, NULL SPACE")
print("="*60)

# ============================================================================
# STEP 1: IDENTIFY PIVOT AND NON-PIVOT COLUMNS
# ============================================================================

print("\n--- STEP 1: PIVOT AND NON-PIVOT COLUMNS ---")

rows, cols = rref_A.shape
pivot_cols = []
non_pivot_cols = []

for i in range(rows):
    for j in range(cols):
        if abs(rref_A[i][j] - 1.0) < 1e-4:
            pivot_cols.append(j)
            break

for j in range(cols):
    if j not in pivot_cols:
        non_pivot_cols.append(j)

print(f"Pivot Columns (Basic Variables): {pivot_cols}")
print(f"Non-Pivot Columns (Free Variables): {non_pivot_cols}")
print(f"Rank = {len(pivot_cols)}, Nullity = {len(non_pivot_cols)}")

# ============================================================================
# STEP 2: FIND PARTICULAR SOLUTION (Ax = b)
# ============================================================================

print("\n--- STEP 2: PARTICULAR SOLUTION (Ax = b) ---")

x_particular = np.zeros(cols)

# Set free variables to 0
for col in non_pivot_cols:
    x_particular[col] = 0.0

# Solve for basic variables
for idx, col in enumerate(pivot_cols):
    x_particular[col] = rref_b[idx][0]

print("Particular solution (setting free variables = 0):")
for i in range(cols):
    if i in pivot_cols:
        print(f"  x{i} = {x_particular[i]:.4f} (basic)")
    else:
        print(f"  x{i} = {x_particular[i]:.4f} (free)")

print(f"\nx_p = {[round(x, 4) for x in x_particular]}")

# ============================================================================
# STEP 3: FIND NULL SPACE BASIS (Solutions to Ax = 0)
# ============================================================================

print("\n--- STEP 3: NULL SPACE BASIS (Ax = 0) ---")

null_vectors = []

for free_col in non_pivot_cols:
    x_null = np.zeros(cols)
    x_null[free_col] = 1.0
    
    for row in range(rows - 1, -1, -1):
        pivot_in_row = -1
        for j in range(cols):
            if abs(rref_A[row][j] - 1.0) < 1e-4:
                pivot_in_row = j
                break
        
        if pivot_in_row != -1 and pivot_in_row != free_col:
            x_null[pivot_in_row] = -rref_A[row][free_col]
    
    null_vectors.append(x_null)

print(f"Dimension of null space = {len(null_vectors)}")
print("Null space basis vector (set free variable = 1):")
for i in range(cols):
    if i in pivot_cols:
        print(f"  x{i} = {null_vectors[0][i]:.4f} (basic)")
    else:
        print(f"  x{i} = {null_vectors[0][i]:.4f} (free = 1)")

print(f"\nv = {[round(x, 4) for x in null_vectors[0]]}")

# ============================================================================
# STEP 4: GENERAL SOLUTION
# ============================================================================

print("\n--- STEP 4: GENERAL SOLUTION ---")

print("General solution: x = x_p + c·v, where c ∈ ℝ")
print("\nIn component form:")
for i in range(cols):
    if i in pivot_cols:
        print(f"  x{i} = {x_particular[i]:.4f} + {null_vectors[0][i]:.4f}·c")
    else:
        print(f"  x{i} = c")

# ============================================================================
# STEP 5: VERIFICATION
# ============================================================================

print("\n--- STEP 5: VERIFICATION ---")

# Verify particular solution
Ax_p = A @ x_particular
print(f"A × x_p = {Ax_p.flatten()}")
print(f"b       = {b.flatten()}")
if np.allclose(Ax_p, b.flatten(), rtol=1e-4):
    print("✓ VERIFIED: A × x_p = b")

# Verify null vector
Av = A @ null_vectors[0]
print(f"\nA × v = {Av.flatten()}")
if np.allclose(Av, 0, atol=1e-4):
    print("✓ VERIFIED: A × v = 0")

# Verify general solution with random c
c_random = 2.5
x_general = x_particular + c_random * null_vectors[0]
Ax_general = A @ x_general
print(f"\nFor c = {c_random}:")
print(f"A × (x_p + c·v) = {Ax_general.flatten()}")
print(f"b                = {b.flatten()}")
if np.allclose(Ax_general, b.flatten(), rtol=1e-4):
    print("✓ VERIFIED: For any c, Ax = b holds")

# ============================================================================
# FINAL ANSWER
# ============================================================================

print("\n" + "="*60)
print("FINAL ANSWER")
print("="*60)

print(f"""
Pivot Columns: {pivot_cols}
Non-Pivot Columns: {non_pivot_cols}

Particular Solution:
x_p = {[round(x, 4) for x in x_particular]}

Null Space Basis:
v = {[round(x, 4) for x in null_vectors[0]]}

General Solution:
x = x_p + c·v,  where c ∈ ℝ

Verification: ✓ All solutions verified
""")

print("="*60)
print("END OF Q1(b)")
print("="*60)

RREF_A [[ 1.      0.      0.      0.     12.5625]
 [ 0.      1.      0.      0.      6.0312]
 [ 0.      0.      1.      0.     -5.0937]
 [ 0.      0.      0.      1.      4.9687]]
RREF_b [[-12.5625]
 [ -6.0312]
 [  7.0937]
 [ -2.9687]]
Q1(b): PIVOT COLUMNS, PARTICULAR SOLUTION, NULL SPACE

--- STEP 1: PIVOT AND NON-PIVOT COLUMNS ---
Pivot Columns (Basic Variables): [0, 1, 2, 3]
Non-Pivot Columns (Free Variables): [4]
Rank = 4, Nullity = 1

--- STEP 2: PARTICULAR SOLUTION (Ax = b) ---
Particular solution (setting free variables = 0):
  x0 = -12.5625 (basic)
  x1 = -6.0312 (basic)
  x2 = 7.0937 (basic)
  x3 = -2.9687 (basic)
  x4 = 0.0000 (free)

x_p = [np.float64(-12.5625), np.float64(-6.0312), np.float64(7.0937), np.float64(-2.9687), np.float64(0.0)]

--- STEP 3: NULL SPACE BASIS (Ax = 0) ---
Dimension of null space = 1
Null space basis vector (set free variable = 1):
  x0 = -12.5625 (basic)
  x1 = -6.0312 (basic)
  x2 = 5.0937 (basic)
  x3 = -4.9687 (basic)
  x4 = 1.0000 (free = 1)

v

In [6]:
# ============================================================================
# Q1(b): PIVOT COLUMNS, PARTICULAR SOLUTION, AND NULL SPACE
# ============================================================================

import numpy as np

# INPUT from Q1(a) results
A = np.array([[-1,0,3,5,-3],[4,-3,3,-4,-3],[-4,1,-4,5,1],[-2,4,0,0,-1]])
b = np.array([[19],[1],[1],[1]])

# RREF from Q1(a)
rref_A = np.array([[1,0,0,0,12.5625],[0,1,0,0,6.0312],[0,0,1,0,-5.0937],[0,0,0,1,4.9687]])
rref_b = np.array([[-12.5625],[-6.0312],[7.0937],[-2.9687]])

rows, cols = rref_A.shape

# ============================================================================
# STEP 1: FIND PIVOT AND NON-PIVOT COLUMNS
# ============================================================================

pivot_cols = []
non_pivot_cols = []

for i in range(rows):
    for j in range(cols):
        if abs(rref_A[i][j] - 1.0) < 1e-4:
            pivot_cols.append(j)
            break

for j in range(cols):
    if j not in pivot_cols:
        non_pivot_cols.append(j)

print("="*60)
print("Q1(b) - PIVOT COLUMNS, PARTICULAR SOLUTION, NULL SPACE")
print("="*60)

print("\n--- STEP 1: PIVOT AND NON-PIVOT COLUMNS ---")
print(f"Pivot Columns: {pivot_cols}")
print(f"Non-Pivot Columns: {non_pivot_cols}")
print(f"Rank = {len(pivot_cols)}, Nullity = {len(non_pivot_cols)}")

# ============================================================================
# STEP 2: FIND PARTICULAR SOLUTION (Ax = b)
# ============================================================================

x_particular = np.zeros(cols)

# Set free variables to 0
for col in non_pivot_cols:
    x_particular[col] = 0.0

# Solve for basic variables
for idx, col in enumerate(pivot_cols):
    x_particular[col] = rref_b[idx][0]

print("\n--- STEP 2: PARTICULAR SOLUTION (Ax = b) ---")
print("Setting free variables = 0:")
for i in range(cols):
    if i in pivot_cols:
        print(f"  x{i} = {x_particular[i]:.4f} (basic)")
    else:
        print(f"  x{i} = {x_particular[i]:.4f} (free)")

print(f"\nx_p = {[round(x, 4) for x in x_particular]}")

# ============================================================================
# STEP 3: FIND NULL SPACE BASIS (Solutions to Ax = 0)
# ============================================================================

null_vectors = []

for free_col in non_pivot_cols:
    x_null = np.zeros(cols)
    x_null[free_col] = 1.0
    
    for row in range(rows):
        if row < len(pivot_cols):
            pivot_in_row = pivot_cols[row]
            x_null[pivot_in_row] = -rref_A[row][free_col]
    
    null_vectors.append(x_null)

print("\n--- STEP 3: NULL SPACE BASIS (Ax = 0) ---")
print(f"Dimension = {len(null_vectors)}")

for idx, vec in enumerate(null_vectors):
    print(f"\nv{idx+1} (set x{non_pivot_cols[idx]} = 1):")
    for i in range(cols):
        if i == non_pivot_cols[idx]:
            print(f"  x{i} = {vec[i]:.4f} (free = 1)")
        elif i in pivot_cols:
            print(f"  x{i} = {vec[i]:.4f} (basic)")

print(f"\nv = {[round(x, 4) for x in null_vectors[0]]}")

print("\n" + "="*60)
print("END OF Q1(b)")
print("="*60)

Q1(b) - PIVOT COLUMNS, PARTICULAR SOLUTION, NULL SPACE

--- STEP 1: PIVOT AND NON-PIVOT COLUMNS ---
Pivot Columns: [0, 1, 2, 3]
Non-Pivot Columns: [4]
Rank = 4, Nullity = 1

--- STEP 2: PARTICULAR SOLUTION (Ax = b) ---
Setting free variables = 0:
  x0 = -12.5625 (basic)
  x1 = -6.0312 (basic)
  x2 = 7.0937 (basic)
  x3 = -2.9687 (basic)
  x4 = 0.0000 (free)

x_p = [np.float64(-12.5625), np.float64(-6.0312), np.float64(7.0937), np.float64(-2.9687), np.float64(0.0)]

--- STEP 3: NULL SPACE BASIS (Ax = 0) ---
Dimension = 1

v1 (set x4 = 1):
  x0 = -12.5625 (basic)
  x1 = -6.0312 (basic)
  x2 = 5.0937 (basic)
  x3 = -4.9687 (basic)
  x4 = 1.0000 (free = 1)

v = [np.float64(-12.5625), np.float64(-6.0312), np.float64(5.0937), np.float64(-4.9687), np.float64(1.0)]

END OF Q1(b)
